# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy with Jenkins

on:
  pull_request:
    branches: [ deploy ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: trigger jenkins job.
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.JENKINS_WEBHOOK_URL }}
        user: "wfg342rrf"
        token: ${{ secrets.JENKINS_API_TOKEN }}
        job: "movieProrject"